"""engineering analytics

Revision ID: 1a1b14c2ef64
Revises: 66fee847027c
Create Date: 2026-09-09 13:46:32.859070

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1a1b14c2ef64"
down_revision: str | Sequence[str] | None = "66fee847027c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_snapshots",
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "succeeded", "failed", name="analytics_snapshot_status"),
            nullable=False,
        ),
        sa.Column("synced_through", sa.DateTime(timezone=True), nullable=True),
        sa.Column("daily_commit_activity", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "daily_pr_issue_activity", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("contributor_activity", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("median_cycle_time_hours", sa.Float(), nullable=True),
        sa.Column("pr_cycle_time_samples", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("open_issues_total", sa.Integer(), nullable=False),
        sa.Column("stale_issues", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("file_hotspots", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("architecture_hotspots", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("commit_sample_size", sa.Integer(), nullable=False),
        sa.Column("hotspot_commit_sample_size", sa.Integer(), nullable=False),
        sa.Column("pr_sample_size", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_snapshots_repository_id"),
        "analytics_snapshots",
        ["repository_id"],
        unique=False,
    )
    # NOTE: autogenerate proposed dropping ix_code_embeddings_embedding_hnsw here —
    # it doesn't understand the hand-written raw-SQL HNSW index from
    # abdb18abe5f8_codebase_indexing_pipeline.py and treats it as unmanaged drift.
    # Same false-positive as every migration since (0005-0008); removed by hand.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analytics_snapshots_repository_id"), table_name="analytics_snapshots")
    op.drop_table("analytics_snapshots")
    # ### end Alembic commands ###
