"""pull request analysis

Revision ID: 505700f39be4
Revises: ab54e430215d
Create Date: 2026-09-09 11:48:31.540627

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "505700f39be4"
down_revision: str | Sequence[str] | None = "ab54e430215d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pull_request_analyses",
        sa.Column("pull_request_id", sa.UUID(), nullable=False),
        sa.Column("head_sha", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "succeeded", "failed", name="pr_analysis_status"),
            nullable=False,
        ),
        sa.Column(
            "risk_level", sa.Enum("low", "medium", "high", name="pr_risk_level"), nullable=True
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("affected_components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("potential_concerns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommended_tests", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("files_analyzed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["pull_request_id"], ["pull_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pull_request_analyses_pull_request_id"),
        "pull_request_analyses",
        ["pull_request_id"],
        unique=False,
    )
    # NOTE: autogenerate proposed dropping ix_code_embeddings_embedding_hnsw here —
    # it doesn't understand the hand-written raw-SQL HNSW index from
    # abdb18abe5f8_codebase_indexing_pipeline.py and treats it as unmanaged drift.
    # See ADR 0004/0005/0006 for the same false-positive; removed by hand.
    op.add_column(
        "pull_requests",
        sa.Column("head_sha", sa.String(length=40), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pull_requests", "head_sha")
    op.drop_index(
        op.f("ix_pull_request_analyses_pull_request_id"), table_name="pull_request_analyses"
    )
    op.drop_table("pull_request_analyses")
    # ### end Alembic commands ###
