"""developer onboarding

Revision ID: 66fee847027c
Revises: 505700f39be4
Create Date: 2026-09-09 12:32:19.330813

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66fee847027c"
down_revision: str | Sequence[str] | None = "505700f39be4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_guides",
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "succeeded", "failed", name="onboarding_guide_status"),
            nullable=False,
        ),
        sa.Column("architecture_overview", sa.Text(), nullable=True),
        sa.Column("common_workflows", sa.Text(), nullable=True),
        sa.Column("authentication_flow", sa.Text(), nullable=True),
        sa.Column("faq", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("important_modules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommended_files", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("key_dependencies", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dev_setup_steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("database_structure", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("learning_path", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_onboarding_guides_repository_id"),
        "onboarding_guides",
        ["repository_id"],
        unique=False,
    )
    op.create_table(
        "onboarding_progress",
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("item_key", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "repository_id", "user_id", "item_key", name="uq_onboarding_progress_repo_user_item"
        ),
    )
    op.create_index(
        op.f("ix_onboarding_progress_repository_id"),
        "onboarding_progress",
        ["repository_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_onboarding_progress_user_id"), "onboarding_progress", ["user_id"], unique=False
    )
    # NOTE: autogenerate proposed dropping ix_code_embeddings_embedding_hnsw here —
    # it doesn't understand the hand-written raw-SQL HNSW index from
    # abdb18abe5f8_codebase_indexing_pipeline.py and treats it as unmanaged drift.
    # Same false-positive as every migration since (0005/0006/0007); removed by hand.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_onboarding_progress_user_id"), table_name="onboarding_progress")
    op.drop_index(op.f("ix_onboarding_progress_repository_id"), table_name="onboarding_progress")
    op.drop_table("onboarding_progress")
    op.drop_index(op.f("ix_onboarding_guides_repository_id"), table_name="onboarding_guides")
    op.drop_table("onboarding_guides")
    # ### end Alembic commands ###
