"""codebase indexing pipeline

Revision ID: abdb18abe5f8
Revises: b3ec059c513c
Create Date: 2026-09-08 12:50:22.326054

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abdb18abe5f8"
down_revision: str | Sequence[str] | None = "b3ec059c513c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Not autogenerated: pgvector's Vector type requires the extension.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_files",
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column("path", sa.String(length=1000), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("imports", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "path", name="uq_code_files_repo_path"),
    )
    op.create_index(
        op.f("ix_code_files_repository_id"), "code_files", ["repository_id"], unique=False
    )
    op.create_table(
        "indexing_jobs",
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued", "running", "succeeded", "failed", "partial", name="indexing_job_status"
            ),
            nullable=False,
        ),
        sa.Column(
            "trigger",
            sa.Enum("initial", "manual", "webhook", name="indexing_trigger"),
            nullable=False,
        ),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column(
            "current_stage",
            sa.Enum(
                "fetching",
                "discovering",
                "filtering",
                "parsing",
                "chunking",
                "embedding",
                "done",
                name="indexing_stage",
            ),
            nullable=True,
        ),
        sa.Column("files_discovered", sa.Integer(), nullable=False),
        sa.Column("files_processed", sa.Integer(), nullable=False),
        sa.Column("files_skipped", sa.Integer(), nullable=False),
        sa.Column("symbols_extracted", sa.Integer(), nullable=False),
        sa.Column("chunks_created", sa.Integer(), nullable=False),
        sa.Column("embeddings_generated", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_indexing_jobs_repository_id"), "indexing_jobs", ["repository_id"], unique=False
    )
    op.create_table(
        "code_symbols",
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("parent_symbol_id", sa.UUID(), nullable=True),
        sa.Column("symbol_type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column("docstring", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["code_files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_symbol_id"], ["code_symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_code_symbols_file_id"), "code_symbols", ["file_id"], unique=False)
    op.create_table(
        "indexing_errors",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=True),
        sa.Column(
            "stage",
            sa.Enum(
                "fetching",
                "discovering",
                "filtering",
                "parsing",
                "chunking",
                "embedding",
                "done",
                name="indexing_stage",
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["indexing_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_indexing_errors_job_id"), "indexing_errors", ["job_id"], unique=False)
    op.create_table(
        "code_chunks",
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("symbol_id", sa.UUID(), nullable=True),
        sa.Column("chunk_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["code_files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["symbol_id"], ["code_symbols.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_code_chunks_file_id"), "code_chunks", ["file_id"], unique=False)
    op.create_table(
        "code_embeddings",
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(1024), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["code_chunks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_id"),
    )
    # ### end Alembic commands ###
    # Not autogenerated: pgvector similarity search needs an ANN index.
    # HNSW over IVFFlat — no training/list-count tuning needed and it
    # performs well even before the table has many rows, which matters for
    # a portfolio-scale dataset. vector_cosine_ops matches the cosine
    # similarity voyage-code-3 embeddings are compared with.
    op.execute(
        "CREATE INDEX ix_code_embeddings_embedding_hnsw ON code_embeddings "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_code_embeddings_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("code_embeddings")
    op.drop_index(op.f("ix_code_chunks_file_id"), table_name="code_chunks")
    op.drop_table("code_chunks")
    op.drop_index(op.f("ix_indexing_errors_job_id"), table_name="indexing_errors")
    op.drop_table("indexing_errors")
    op.drop_index(op.f("ix_code_symbols_file_id"), table_name="code_symbols")
    op.drop_table("code_symbols")
    op.drop_index(op.f("ix_indexing_jobs_repository_id"), table_name="indexing_jobs")
    op.drop_table("indexing_jobs")
    op.drop_index(op.f("ix_code_files_repository_id"), table_name="code_files")
    op.drop_table("code_files")
    # ### end Alembic commands ###
